### Register a New Account (Should pass rules successfully)
POST http://localhost:8082/api/auth/register
Content-Type: application/json

{
  "name": "Alex",
  "email": "alex@example.com",
  "password": "mySecurePassword123"
}

### Test Duplicate Email Rejection (Should return 400 Bad Request)
POST http://localhost:8082/api/auth/register
Content-Type: application/json

{
  "name": "Alex Fake",
  "email": "alex@example.com",
  "password": "differentPassword"
}

### User Successful Login (Should return 200 with JWT)
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "email": "alex@example.com",
  "password": "mySecurePassword123"
}

### User Invalid Login Credentials (Should return 401 Unauthorized)
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "email": "alex@example.com",
  "password": "wrongPassword"
}