export default function ReportCard({ title, items = [] }) {
  const hasData = Array.isArray(items) && items.length > 0;

  return (
    <section className="card report-card">
      <div className="section-heading">
        <h2>{title}</h2>
        <p>Generated by MongoDB aggregation endpoints.</p>
      </div>

      {!hasData ? (
        <div className="report-empty">
          <p>No report data available.</p>
        </div>
      ) : (
        <div className="report-list">
          {items.map((item, index) => {
            const label = item.label || item._id || 'Unassigned';
            const count = item.count ?? item.total ?? 0;

            return (
              <div className="report-row" key={label || index}>
                <span className="report-label">{label}</span>
                <span className="report-badge">{count}</span>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}