spring.application.name=AssetTracker

## This tells Spring Boot to look at your @Indexed tags and automatically build them inside MongoDB on startup:
spring.data.mongodb.auto-index-creation=true

server.port=8082

# The absolute unified string configuration format
spring.data.mongodb.uri=mongodb://desk_user:DeskPassword123@localhost:27017/support_desk_db?authSource=support_desk_db